project_id = "whaleinsight-pro-mvp"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
port = 54323

[api]
port = 54321

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
